backend:
  name: github
  repo: RetailPlaybook/retailplaybook-site   # your GitHub repo (Owner/Repo)
  branch: main
  base_url: https://rp-cms-auth.james-c4d.workers.dev
  auth_endpoint: /auth

media_folder: "assets/uploads"    # where uploaded files are stored in repo
public_folder: "/assets/uploads"  # how they are served on site

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title",   name: "title",   widget: "string" }
      - { label: "Date",    name: "date",    widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body",    name: "body",    widget: "markdown" }
