backend:
  name: github
  repo: retailplaybook/retailplaybook-site         # e.g., RetailPlaybook/retailplaybook-site
  branch: main
  base_url: https://rp-cms-auth.james-c4d.workers.dev
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"                      # ← unique
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body (Markdown)", name: "body", widget: "markdown" }

  - name: "registry"                   # ← unique
    label: "Publications List"
    files:
      - file: "posts/posts.json"
        label: "Homepage Publications"
        name: "publications"
        format: "json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD" }
              - { label: "Summary", name: "summary", widget: "text", required: false }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Image", name: "image", widget: "image", required: false }
              - { label: "Tags", name: "tags", widget: "list", required: false }
