backend:
  name: github
  repo: retailplaybook/retailplaybook-site
  branch: main
  base_url: https://rp-cms-auth.james-c4d.workers.dev
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    files:
      - file: "posts/posts.json"
        label: "Publications"
        name: "publications"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Summary", name: "summary", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Tags", name: "tags", widget: "list", required: false }
